import type { NextPage } from "next";
import Head from "next/head";
import Hero from "./components/Hero";
import Profile from "./components/Profile";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto min-h-screen flex-col items-center overflow-hidden bg-[#F5F7FF] dark:bg-[#141D2F]">
        <Hero />
        <Profile />
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
